# Neden NumPy?

In [ ]:
a = [1,2,3,4]
b = [2,3,4,5]

In [ ]:
ab = []

for i in range(0 , len(a)):
    ab.append(a[i]*b[i])
    
ab

In [7]:
import numpy as np

In [16]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [17]:
a * b

array([ 2,  6, 12, 20])

# NumPy Array'i Oluşturmak

In [18]:
import numpy as np

In [19]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [20]:
a = np.array([1,2,3,4,5])

In [21]:
type(a)

numpy.ndarray

In [31]:
np.array([3.14, 4, 2, 13], dtype = "int") #int or float32 

array([ 3,  4,  2, 13])

In [27]:
#sifirdan array oluşturma

In [29]:
np.zeros(10, dtype = "int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
np.ones((4,4), dtype = "int")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [37]:
np.full((3,5),3) #Tek sayıdan oluşması için

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

## Arange fonksiyonu

In [39]:
np.arange(0,31,3) # Doğrusal bir dizi için

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

## Linspace fonksiyonu

In [43]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

## Random.normal fonksiyonu

In [47]:
np.random.normal(10, 4, (3,4)) 
#Belirli bir dağılım yapısına uygun olan sayılar oluşturmak için kullanılır.
#İstatistik teorisindeki normal dağılım gibi
#Belirli bir standart sapma belirli bir ortalama verilir ve array veya 2 boyutlu bir array'in bilgisini tanımlarız.
#Ortalaması 10 
#Standard sapması 4
#3e 4lük matris tanımlayabiliriz

array([[11.77757102,  7.45312677,  6.87482163,  8.59683758],
       [-0.78211698, 12.62982993,  4.76325902, 11.07096177],
       [12.64634124,  3.28936555,  9.14844968,  1.80896621]])

## Random.randint Fonksiyonu 

In [49]:
np.random.randint(0,10, (3,3))
#Belirli bir aralıkta array oluşturmaya yarar.

array([[2, 1, 3],
       [0, 0, 0],
       [7, 9, 2]])

# Numpy Array'inin Özellikleri

* **ndim**: _boyut sayısı_
* **shape**: _boyut bilgisi_
* **size** : _toplam eleman sayısı_
* **dtype** : _dtype array veri tipi_

In [51]:
import numpy as np

In [52]:
np.random.randint(10 , size = 10)

array([6, 0, 3, 2, 6, 6, 7, 8, 3, 7])

In [53]:
a = np.random.randint(10 , size = 10)

In [59]:
a.ndim

1

In [60]:
a.shape

(10,)

In [61]:
a.size

10

In [62]:
a.dtype

dtype('int64')

In [63]:
b = np.random.randint(10 , size = (3,5))

In [64]:
b

array([[6, 8, 1, 5, 6],
       [2, 5, 3, 5, 8],
       [5, 0, 6, 9, 4]])

In [65]:
b.ndim

2

In [66]:
b.shape

(3, 5)

In [67]:
b.size

15

In [68]:
b.dtype

dtype('int64')

## Yeniden Şekillendirme (reshaping)

In [69]:
import numpy as np

In [72]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
a.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
a.ndim #vektör

1

In [77]:
b = a.reshape((1,9))

In [78]:
b.ndim

2

## Array Birleştirme (Concatenation)

In [1]:
import numpy as np

# Tek boyut

In [2]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [4]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [5]:
z = np.array([7,8,9])

In [6]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# İki boyut

In [7]:
a = np.array([[1,2,3],
              [4,5,6]])

In [8]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [12]:
np.concatenate([a,a] , axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## Array Ayırma (Splitting)

In [13]:
import numpy as np

In [14]:
x = np.array([1,2,3,99,99,3,2,1])

In [15]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [16]:
a,b,c = np.split(x,[3,5])

In [17]:
a

array([1, 2, 3])

In [18]:
b

array([99, 99])

In [19]:
c

array([3, 2, 1])

In [20]:
# İki Boyutlu Array

In [21]:
m = np.arange(16).reshape(4,4)

In [22]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [30]:
np.vsplit(m, [2] )

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [31]:
ust,alt =np.vsplit(m, [2] )

In [32]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [33]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [34]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [37]:
sag , sol = np.hsplit(m,[2])

In [38]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [39]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

## Array Sıralama(Sorting )

In [40]:
import numpy as np

In [41]:
v = np.array([2,1,4,3,5])

In [42]:
v

array([2, 1, 4, 3, 5])

In [43]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [45]:
v #orj hali sıralı değil

array([2, 1, 4, 3, 5])

In [46]:
v.sort()

In [48]:
v #orj hali sıralı

array([1, 2, 3, 4, 5])

In [49]:
#İki Boyutlu Array Siralama

In [53]:
m = np.random.normal(20,5,(3,3))

In [55]:
m

array([[20.98466023, 24.0835741 , 20.83411449],
       [15.68604917, 24.73182149, 28.08306218],
       [19.57587293,  9.99425171, 22.97528846]])

In [56]:
np.sort(m , axis = 1)

array([[20.83411449, 20.98466023, 24.0835741 ],
       [15.68604917, 24.73182149, 28.08306218],
       [ 9.99425171, 19.57587293, 22.97528846]])

In [57]:
np.sort(m, axis = 0)

array([[15.68604917,  9.99425171, 20.83411449],
       [19.57587293, 24.0835741 , 22.97528846],
       [20.98466023, 24.73182149, 28.08306218]])

## Index ile Elemanlara Erişmek

In [1]:
import numpy as np 
a = np.random.randint(10, size = 10)
a

array([1, 4, 6, 2, 7, 5, 6, 7, 8, 0])

In [5]:
a[0]

1

In [6]:
a[-1]

0

In [7]:
m = np.random.randint(10, size = (3,5))
m

array([[4, 3, 5, 2, 5],
       [5, 5, 4, 0, 6],
       [3, 5, 2, 6, 3]])

In [9]:
m[0,0]

4

In [10]:
m[1,1]

5

In [11]:
m[2,3]

6

In [12]:
m[1,1]= 99

In [13]:
m

array([[ 4,  3,  5,  2,  5],
       [ 5, 99,  4,  0,  6],
       [ 3,  5,  2,  6,  3]])

## Slicing İle Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [14]:
import numpy as np

In [15]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [16]:
a[0:3]

array([20, 21, 22])

In [18]:
a[:3]

array([20, 21, 22])

In [23]:
a[::-1]

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20])

In [24]:
a[1::2]

array([21, 23, 25, 27, 29])

In [25]:
a[0::2]

array([20, 22, 24, 26, 28])

In [26]:
# İki Boyutlu Slice İşlemleri

In [31]:
m = np.random.randint(10, size = (5,5))
m

array([[2, 6, 8, 6, 5],
       [5, 6, 4, 4, 1],
       [4, 5, 7, 5, 1],
       [9, 5, 1, 0, 2],
       [3, 8, 6, 2, 2]])

In [32]:
m[:,0]

array([2, 5, 4, 9, 3])

In [33]:
m[:,1]

array([6, 6, 5, 5, 8])

In [34]:
m[1:3, 0:2]

array([[5, 6],
       [4, 5]])

## Alt Küme Üzerinde İşlem yapmak 

In [35]:
import numpy as np

In [36]:
a = np.random.randint(10, size = (5,5))
a

array([[1, 6, 7, 6, 8],
       [7, 3, 1, 2, 0],
       [9, 8, 3, 8, 6],
       [9, 3, 6, 7, 3],
       [5, 3, 5, 3, 4]])

In [37]:
alt_a = a[0:3,0:2]
alt_a

array([[1, 6],
       [7, 3],
       [9, 8]])

In [38]:
alt_a[0,0] = 99999
alt_a[1,1] = 888

In [39]:
a

array([[99999,     6,     7,     6,     8],
       [    7,   888,     1,     2,     0],
       [    9,     8,     3,     8,     6],
       [    9,     3,     6,     7,     3],
       [    5,     3,     5,     3,     4]])

In [40]:
m = np.random.randint(10, size = (5,5))
m

array([[8, 3, 5, 3, 3],
       [4, 3, 1, 6, 8],
       [8, 6, 5, 5, 5],
       [6, 7, 9, 9, 9],
       [5, 7, 9, 9, 1]])

In [41]:
alt_b = m[0:3, 0:2].copy()
alt_b

array([[8, 3],
       [4, 3],
       [8, 6]])

In [42]:
alt_b[0,0] = 9999
alt_b

array([[9999,    3],
       [   4,    3],
       [   8,    6]])

In [43]:
m

array([[8, 3, 5, 3, 3],
       [4, 3, 1, 6, 8],
       [8, 6, 5, 5, 5],
       [6, 7, 9, 9, 9],
       [5, 7, 9, 9, 1]])

## Fancy Index ile Elemanlara Erişmek

In [45]:
import numpy as np
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [46]:
v[1]

3

In [47]:
v[3]

9

In [48]:
v[5]

15

In [49]:
[v[1],v[3],v[5]]

[3, 9, 15]

In [50]:
al_getir = [1,3,5]

In [51]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [53]:
v[al_getir] #ÖNEMLİ!!!

array([ 3,  9, 15])

In [54]:
#İki boyutta fancy

In [55]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [56]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [57]:
m[satir,sutun]

array([1, 5])

In [58]:
#basit index ile fancy index

In [59]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [60]:
m[0, [1,2]]

array([1, 2])

In [64]:
#slice ile fancy

In [63]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

## **Koşullu Eleman İşlemleri**

In [66]:
import numpy as np
v = np.array([1,2,3,4,5])

In [68]:
v < 3

array([ True,  True, False, False, False])

In [69]:
 v[v < 3]

array([1, 2])

In [70]:
 v[v > 3]

array([4, 5])

In [71]:
 v[v >= 3]

array([3, 4, 5])

In [73]:
 v[v == 3]

array([3])

In [74]:
 v[v != 3]

array([1, 2, 4, 5])

## Matematiksel İşlemler

In [75]:
import numpy as np
v = np.array([1,2,3,4,5])

In [80]:
v + 1

array([2, 3, 4, 5, 6])

In [76]:
v - 1

array([0, 1, 2, 3, 4])

In [77]:
v * 5

array([ 5, 10, 15, 20, 25])

In [79]:
v / 10

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [81]:
#ufunc

In [82]:
np.subtract(v , 1)

array([0, 1, 2, 3, 4])

In [83]:
np.add(v, 1)

array([2, 3, 4, 5, 6])

In [84]:
np.multiply(v , 5)

array([ 5, 10, 15, 20, 25])

In [85]:
np.divide(v, 3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [86]:
v ** 2

array([ 1,  4,  9, 16, 25])

In [87]:
np.power(v, 3)

array([  1,   8,  27,  64, 125])

In [88]:
v % 2

array([1, 0, 1, 0, 1])

In [89]:
np.mod(v,2)

array([1, 0, 1, 0, 1])

In [90]:
np.absolute([np.array([-3])])

array([[3]])

In [91]:
np.sin(360)

0.9589157234143065

In [92]:
np.cos(180)

-0.5984600690578581

In [93]:
v = np.array([1,2,3])

In [94]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [95]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [96]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [99]:
?np

Type:        module
String form: <module 'numpy' from '/opt/anaconda3/lib/python3.9/site-packages/numpy/__init__.py'>
File:        /opt/anaconda3/lib/python3.9/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = 

## İstatiksel Hesaplamalar 

In [100]:
#cheatsheet

In [101]:
np.mean(v,axis=0)

2.0

In [102]:
v.sum()

6

In [103]:
v.min()

1

In [104]:
v.max(axis=0)

3

In [105]:
np.var(v)

0.6666666666666666

In [107]:
np.std(v,axis=0)

0.816496580927726

In [109]:
#v.corrcoef()

np.mean(arr,axis=0) | Returns mean along specific axis 
arr.sum() | Returns sum of arr 
arr.min() | Returns minimum value of arr 
arr.max(axis=0) | Returns maximum value of specific axis 
np.var(arr) | Returns the variance of array 
np.std(arr,axis=1) | Returns the standard deviation of specific axis 
arr.corrcoef() | Returns correlation coefficient of array



## NumPy ile İki Bilinmeyenli Denklem Çözümü

In [111]:
import numpy as np

* 5 * x0 + x1 = 12
* x0 + 3 * x1 = 10

In [113]:
a = np.array([[5,1],[1,3]])
b = np.array([12,10])

In [114]:
a

array([[5, 1],
       [1, 3]])

In [115]:
b

array([12, 10])

In [117]:
x = np.linalg.solve(a, b)
x

array([1.85714286, 2.71428571])