# Pandas Serisi Oluşturmak

In [1]:
import pandas as pd

In [2]:
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
seri = pd.Series([1,2,3,4,5])

In [4]:
type(seri)

pandas.core.series.Series

In [5]:
seri.axes

[RangeIndex(start=0, stop=5, step=1)]

In [6]:
seri.dtype

dtype('int64')

In [7]:
seri.size

5

In [8]:
seri.ndim

1

In [9]:
seri.values

array([1, 2, 3, 4, 5])

In [10]:
seri.head()

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [11]:
seri.head(3)

0    1
1    2
2    3
dtype: int64

In [13]:
seri.tail(3)

2    3
3    4
4    5
dtype: int64

## Index İsimlendirmesi

In [15]:
pd.Series([99,22,332,94,5])

0     99
1     22
2    332
3     94
4      5
dtype: int64

In [16]:
pd.Series([99,22,332,94,5], index =[1,3,5,7,9])

1     99
3     22
5    332
7     94
9      5
dtype: int64

In [17]:
pd.Series([99,22,332,94,5],index = ["a","b","c","d","e"])

a     99
b     22
c    332
d     94
e      5
dtype: int64

In [18]:
seri = pd.Series([99,22,332,94,5],index = ["a","b","c","d","e"])

In [19]:
seri["a"]

99

In [20]:
seri["a":"c"]

a     99
b     22
c    332
dtype: int64

## Sözlük Üzerinden Liste Oluşturmak

In [22]:
 sozluk = pd.Series ({"reg":10,"log":11,"cart":12})

In [23]:
sozluk

reg     10
log     11
cart    12
dtype: int64

## İki seriyi birleştirerek seri oluşturma

In [24]:
pd.concat([seri,seri])

a     99
b     22
c    332
d     94
e      5
a     99
b     22
c    332
d     94
e      5
dtype: int64

## Eleman İşlemleri

In [26]:
import numpy as np

In [27]:
a = np.array([1,2,33,444,5])
seri = pd.Series(a)
seri

0      1
1      2
2     33
3    444
4      5
dtype: int64

In [28]:
seri[0]

1

In [30]:
seri[0:3]

0     1
1     2
2    33
dtype: int64

In [32]:
seri = pd.Series([121,200,150,99],
                 index = ["reg","loj","cart","rf"] )

In [33]:
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [34]:
seri.index

Index(['reg', 'loj', 'cart', 'rf'], dtype='object')

In [35]:
seri.keys

<bound method Series.keys of reg     121
loj     200
cart    150
rf       99
dtype: int64>

In [36]:
list(seri.items())

[('reg', 121), ('loj', 200), ('cart', 150), ('rf', 99)]

In [37]:
seri.values

array([121, 200, 150,  99])

## Eleman Sorgulama

In [38]:
"reg" in seri

True

In [39]:
"a" in seri

False

In [40]:
seri["reg"]

121

## Fancy ile eleman seçme

In [41]:
serii = ["reg"]
seri[serii]

reg    121
dtype: int64

In [42]:
seri[["rf","reg"]]

rf      99
reg    121
dtype: int64

In [43]:
seri["reg"] = 130

In [44]:
seri["reg"]

130

In [45]:
seri["reg":"loj"]

reg    130
loj    200
dtype: int64

# Pandas DataFrame Oluşturma 

* Yapısal veritipidir
* Excel'e benzerdir

In [46]:
import pandas as pd

In [47]:
l = [1,2,39,67,90]

In [48]:
l

[1, 2, 39, 67, 90]

In [51]:
pd.DataFrame(l, columns = ["degisken_ismi"])

degisken_ismi
0              1
1              2
2             39
3             67
4             90

In [54]:
import numpy as np
m = np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
pd.DataFrame(m, columns = ["var1","var2","var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

## Df isimlendirme

In [57]:
df = pd.DataFrame(m, columns = ["var1","var2","var3"])

In [58]:
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [60]:
df.columns =("deg1","deg2","deg3")

In [61]:
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

**Özellikleri**

In [62]:
type(df)

pandas.core.frame.DataFrame

In [63]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='object')]

In [64]:
df.shape

(3, 3)

In [65]:
df.ndim

2

In [66]:
df.size

9

In [67]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
type(df.values)

numpy.ndarray

In [69]:
df.head()

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [71]:
df.tail(1)

deg1  deg2  deg3
2     7     8     9

In [72]:
a = np.array([1,2,3,4,5])

In [73]:
pd.DataFrame(a, columns = ["deg1"])

deg1
0     1
1     2
2     3
3     4
4     5

## Eleman İşlemleri

In [80]:
import numpy as np
s1 = np.random.randint(10,size = 5)
s2 = np.random.randint(10,size = 5)
s3 = np.random.randint(10,size = 5)

In [81]:
s1

array([6, 4, 2, 5, 8])

In [82]:
s2

array([2, 6, 6, 1, 4])

In [83]:
s3

array([1, 5, 6, 7, 9])

In [86]:
sozluk = {"var1" : s1,"var2" : s2,"var3" : s3 }

In [87]:
sozluk

{'var1': array([6, 4, 2, 5, 8]),
 'var2': array([2, 6, 6, 1, 4]),
 'var3': array([1, 5, 6, 7, 9])}

In [105]:
df = pd.DataFrame(sozluk)

In [89]:
df

var1  var2  var3
0     6     2     1
1     4     6     5
2     2     6     6
3     5     1     7
4     8     4     9

In [90]:
df[0:1]

var1  var2  var3
0     6     2     1

In [91]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [106]:
df.index = ["a","b","c","d","e"]

In [93]:
df

var1  var2  var3
a     6     2     1
b     4     6     5
c     2     6     6
d     5     1     7
e     8     4     9

 ## Silme

In [107]:
df.drop("a", axis = 0)

var1  var2  var3
b     4     6     5
c     2     6     6
d     5     1     7
e     8     4     9

In [95]:
df

var1  var2  var3
a     6     2     1
b     4     6     5
c     2     6     6
d     5     1     7
e     8     4     9

In [108]:
df.drop("a", axis = 0, inplace = True)
# axis = satırı veya sütunu belirtir

In [109]:
df

var1  var2  var3
b     4     6     5
c     2     6     6
d     5     1     7
e     8     4     9

In [110]:
# Fancy ile

In [111]:
l = ["c","e"]

In [112]:
 df.drop(l,axis = 0)

var1  var2  var3
b     4     6     5
d     5     1     7

In [113]:
# Değişkenler İçin

In [114]:
df

var1  var2  var3
b     4     6     5
c     2     6     6
d     5     1     7
e     8     4     9

In [115]:
"var1" in df

True

In [116]:
l = ["var1","var4","var2"]

In [117]:
for i in l:
    print(i in df)

True
False
True


In [118]:
df

var1  var2  var3
b     4     6     5
c     2     6     6
d     5     1     7
e     8     4     9

In [119]:
df["var1"]

b    4
c    2
d    5
e    8
Name: var1, dtype: int64

In [120]:
 df["var4"] = df["var1"] / df["var2"]

In [121]:
df

var1  var2  var3      var4
b     4     6     5  0.666667
c     2     6     6  0.333333
d     5     1     7  5.000000
e     8     4     9  2.000000

In [122]:
#Değişken Silme

In [123]:
df.drop("var4", axis =1)

var1  var2  var3
b     4     6     5
c     2     6     6
d     5     1     7
e     8     4     9

In [124]:
df

var1  var2  var3      var4
b     4     6     5  0.666667
c     2     6     6  0.333333
d     5     1     7  5.000000
e     8     4     9  2.000000

In [125]:
df.drop("var4", axis =1, inplace = True)

In [126]:
df

var1  var2  var3
b     4     6     5
c     2     6     6
d     5     1     7
e     8     4     9

In [127]:
l = ["var1","var2"]

In [128]:
df.drop(l, axis =1)

var3
b     5
c     6
d     7
e     9

In [129]:
df

var1  var2  var3
b     4     6     5
c     2     6     6
d     5     1     7
e     8     4     9

# _Gözlem ve Değişken Seçimi: loc & iloc_

In [130]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30,size=(10,3))
df = pd.DataFrame(m , columns = ["var1","var2","var3"])
df

var1  var2  var3
0    17    27     9
1     3    12    28
2     7    20    19
3    15     8     3
4    13    18     2
5    25    15    25
6    28     6     6
7     1    15    10
8    14     8     5
9     6     3    28

## loc: Tanımlandığı şekli ile seçim yapmak için kullanılır.

In [131]:
df.loc[0:3]

var1  var2  var3
0    17    27     9
1     3    12    28
2     7    20    19
3    15     8     3

## iloc: Alışık olduğumuz indeksleme mantığıyla işlem yapar.

In [132]:
df.iloc[0:3]

var1  var2  var3
0    17    27     9
1     3    12    28
2     7    20    19

In [133]:
df.iloc[0,0]

17

In [134]:
df.iloc[:2,:3]

var1  var2  var3
0    17    27     9
1     3    12    28

In [137]:
df.loc[0:3,"var3"]

0     9
1    28
2    19
3     3
Name: var3, dtype: int64

* Mutlak bir şekilde değişken ismi veya gözlem birimleriyle yani indekslerin isimleriyle seçme işlemlerinda **loc** tercih edilir.
* İndeksli seçim yaklaşımında(klasik tip) **iloc** tercih edilir.

In [139]:
df.iloc[0:3,1:3] 

var2  var3
0    27     9
1    12    28
2    20    19

In [140]:
df.iloc[0:3]["var3"]

0     9
1    28
2    19
Name: var3, dtype: int64

 # Koşullu Eleman İşlemleri 

In [141]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30,size=(10,3))
df = pd.DataFrame(m , columns = ["var1","var2","var3"])
df

var1  var2  var3
0    17    14    28
1    10    29     7
2    19    16    27
3    28    16     6
4    10     8     8
5    27    15     2
6    15    20    24
7    14    17     2
8     1     2     1
9    16    16    14

In [142]:
df["var1"]

0    17
1    10
2    19
3    28
4    10
5    27
6    15
7    14
8     1
9    16
Name: var1, dtype: int64

In [143]:
df

var1  var2  var3
0    17    14    28
1    10    29     7
2    19    16    27
3    28    16     6
4    10     8     8
5    27    15     2
6    15    20    24
7    14    17     2
8     1     2     1
9    16    16    14

In [144]:
df.var1

0    17
1    10
2    19
3    28
4    10
5    27
6    15
7    14
8     1
9    16
Name: var1, dtype: int64

In [147]:
df[df.var1 > 15]

0    17
2    19
3    28
5    27
9    16
Name: var1, dtype: int64

In [150]:
df[(df.var1 > 15) & (df.var3<10)]

var1  var2  var3
3    28    16     6
5    27    15     2

In [157]:
df.loc[(df.var1 > 15) , ["var1","var2"]]
# df[(df.var1 > 15)][["var1","var2"]]

var1  var2
0    17    14
2    19    16
3    28    16
5    27    15
9    16    16

# Birleştirme(Join) İşlemleri

In [160]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30,size=(5,3))
df1 = pd.DataFrame(m , columns = ["var1","var2","var3"])
df1

var1  var2  var3
0     1    29    15
1    24     7    22
2    28    25    28
3    23     4     9
4     8    22    19

In [161]:
df2 = df1 + 99

In [162]:
df2

var1  var2  var3
0   100   128   114
1   123   106   121
2   127   124   127
3   122   103   108
4   107   121   118

In [164]:
pd.concat([df1,df2])
# index bakımından hatalı

var1  var2  var3
0     1    29    15
1    24     7    22
2    28    25    28
3    23     4     9
4     8    22    19
0   100   128   114
1   123   106   121
2   127   124   127
3   122   103   108
4   107   121   118

In [166]:
?pd.concat
#Çözüm yolu olup olmadığına bakıyoruz

Signature:
pd.concat(
    objs: 'Iterable[NDFrame] | Mapping[Hashable, NDFrame]',
    axis=0,
    join='outer',
    ignore_index: 'bool' = False,
    keys=None,
    levels=None,
    names=None,
    verify_integrity: 'bool' = False,
    sort: 'bool' = False,
    copy: 'bool' = True,
) -> 'FrameOrSeriesUnion'
Docstring:
Concatenate pandas objects along a particular axis with optional set logic
along the other axes.

Can also add a layer of hierarchical indexing on the concatenation axis,
which may be useful if the labels are the same (or overlapping) on
the passed axis number.

Parameters
----------
objs : a sequence or mapping of Series or DataFrame objects
    If a mapping is passed, the sorted keys will be used as the `keys`
    argument, unless it is passed, in which case the values will be
    selected (see below). Any None objects will be dropped silently unless
    they are all None in which case a ValueError will be raised.
axis : {0/'index', 1/'columns'}, default 0
    The axis 

In [168]:
pd.concat([df1,df2],ignore_index= True)

var1  var2  var3
0     1    29    15
1    24     7    22
2    28    25    28
3    23     4     9
4     8    22    19
5   100   128   114
6   123   106   121
7   127   124   127
8   122   103   108
9   107   121   118

In [169]:
df1.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [172]:
df2.columns = ["var1","var2","deg3"]

In [173]:
df2

var1  var2  deg3
0   100   128   114
1   123   106   121
2   127   124   127
3   122   103   108
4   107   121   118

In [174]:
df1

var1  var2  var3
0     1    29    15
1    24     7    22
2    28    25    28
3    23     4     9
4     8    22    19

In [175]:
pd.concat([df1,df2])

var1  var2  var3   deg3
0     1    29  15.0    NaN
1    24     7  22.0    NaN
2    28    25  28.0    NaN
3    23     4   9.0    NaN
4     8    22  19.0    NaN
0   100   128   NaN  114.0
1   123   106   NaN  121.0
2   127   124   NaN  127.0
3   122   103   NaN  108.0
4   107   121   NaN  118.0

In [178]:
pd.concat([df1,df2], join = "inner", ignore_index = True)
# Kesişimlere göre birleştirir

var1  var2
0     1    29
1    24     7
2    28    25
3    23     4
4     8    22
5   100   128
6   123   106
7   127   124
8   122   103
9   107   121

In [184]:
# pd.concat([df1, df2], join_axes = [df2.columns])

## İleri Birleştirme İşlemleri

In [4]:
import pandas as pd 

In [186]:
#birebir birlestirme

In [5]:
df1 = pd.DataFrame({'calisanlar':['Ali','Veli','Ayse','Fatma'],
                    'grup':['Muhasebe','Muhendislik','Muhendislik','İK']})
df1

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           İK

In [17]:
df2 = pd.DataFrame({'calisanlar':['Ayse','Ali','Veli','Fatma'],
                    'ilk_giris':[2010,2009,2014,2019]})
df2

calisanlar  ilk_giris
0       Ayse       2010
1        Ali       2009
2       Veli       2014
3      Fatma       2019

In [18]:
pd.merge(df1,df2)

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [14]:
pd.merge(df1,df2,on="calisanlar")

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2010
1       Veli  Muhendislik       2009
2       Ayse  Muhendislik       2014
3      Fatma           İK       2019

In [193]:
#coktan teke

In [19]:
df3 = pd.merge(df1,df2)
df3

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [23]:
df4 = pd.DataFrame({'grup':['Muhasebe', 'Muhendislik', 'İK'],
                    'mudur':['Caner', 'Mustafa', 'Berkcan']})
df4

grup    mudur
0     Muhasebe    Caner
1  Muhendislik  Mustafa
2           İK  Berkcan

In [24]:
pd.merge(df3,df4)

calisanlar         grup  ilk_giris    mudur
0        Ali     Muhasebe       2009    Caner
1       Veli  Muhendislik       2014  Mustafa
2       Ayse  Muhendislik       2010  Mustafa
3      Fatma           İK       2019  Berkcan

In [22]:
# coktan coka

In [25]:
df5 = pd.DataFrame({'grup':['Muhasebe','Muhasebe' ,
                            'Muhendislik','Muhendislik', 'İK', 'İK'],
                    'yetenekler':['matematik', 'excel', 'kodlama','linux', 'excel','yonetim']})
df5

grup yetenekler
0     Muhasebe  matematik
1     Muhasebe      excel
2  Muhendislik    kodlama
3  Muhendislik      linux
4           İK      excel
5           İK    yonetim

In [26]:
df1

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           İK

In [27]:
pd.merge(df1,df5)

calisanlar         grup yetenekler
0        Ali     Muhasebe  matematik
1        Ali     Muhasebe      excel
2       Veli  Muhendislik    kodlama
3       Veli  Muhendislik      linux
4       Ayse  Muhendislik    kodlama
5       Ayse  Muhendislik      linux
6      Fatma           İK      excel
7      Fatma           İK    yonetim

# Toplulaştırma ve Gruplama (Aggregation & Grouping)

Basit Toplulaştırma Fonksiyonları: 
* count()
* first()
* last()
* mean()
* median()
* min()
* max()
* std()
* var()
* sum()

In [29]:
import seaborn as sns

In [30]:
?sns.load_dataset

Signature: sns.load_dataset(name, cache=True, data_home=None, **kws)
Docstring:
Load an example dataset from the online repository (requires internet).

This function provides quick access to a small number of example datasets
that are useful for documenting seaborn or generating reproducible examples
for bug reports. It is not necessary for normal usage.

Note that some of the datasets have a small amount of preprocessing applied
to define a proper ordering for categorical variables.

Use :func:`get_dataset_names` to see a list of available datasets.

Parameters
----------
name : str
    Name of the dataset (``{name}.csv`` on
    https://github.com/mwaskom/seaborn-data).
cache : boolean, optional
    If True, try to load from the local cache first, and save to the cache
    if a download is required.
data_home : string, optional
    The directory in which to cache data; see :func:`get_data_home`.
kws : keys and values, optional
    Additional keyword arguments are passed to passed thr

In [36]:
df = sns.load_dataset("planets")
df

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [33]:
df.shape

(1035, 6)

In [34]:
df.ndim

2

In [35]:
df.mean()

/var/folders/bl/gp_zgv517j37tq1tqrg414vr0000gn/T/ipykernel_89775/3698961737.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.mean()


number               1.785507
orbital_period    2002.917596
mass                 2.638161
distance           264.069282
year              2009.070531
dtype: float64

In [38]:
df["mass"].std()

3.8186166509616046

In [41]:
df.describe()

number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [42]:
df.describe().T

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0

In [45]:
df.dropna().describe().T
# NaN 'ları çıkartır

count         mean          std        min         25%  \
number          498.0     1.734940     1.175720     1.0000     1.00000   
orbital_period  498.0   835.778671  1469.128259     1.3283    38.27225   
mass            498.0     2.509320     3.636274     0.0036     0.21250   
distance        498.0    52.068213    46.596041     1.3500    24.49750   
year            498.0  2007.377510     4.167284  1989.0000  2005.00000   

                     50%        75%      max  
number             1.000     2.0000      6.0  
orbital_period   357.000   999.6000  17337.5  
mass               1.245     2.8675     25.0  
distance          39.940    59.3325    354.0  
year            2009.000  2011.0000   2014.0

## Gruplama İşlemleri

In [46]:
df = pd.DataFrame({'gruplar':['A','B','C','A','B','C'],
                  'veri': [10,11,52,23,43,55]}, columns=['gruplar','veri'])
df

gruplar  veri
0       A    10
1       B    11
2       C    52
3       A    23
4       B    43
5       C    55

In [47]:
df.groupby("gruplar")

In [48]:
df.groupby("gruplar").mean()

veri
gruplar      
A        16.5
B        27.0
C        53.5

In [49]:
df.groupby("gruplar").sum()

veri
gruplar      
A          33
B          54
C         107

In [50]:
df = sns.load_dataset("planets")
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [56]:
df.groupby("method")["orbital_period"].mean()

method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64

In [57]:
df.groupby("method")["orbital_period"].describe()

count           mean            std  \
method                                                               
Astrometry                       2.0     631.180000     544.217663   
Eclipse Timing Variations        9.0    4751.644444    2499.130945   
Imaging                         12.0  118247.737500  213978.177277   
Microlensing                     7.0    3153.571429    1113.166333   
Orbital Brightness Modulation    3.0       0.709307       0.725493   
Pulsar Timing                    5.0    7343.021201   16313.265573   
Pulsation Timing Variations      1.0    1170.000000            NaN   
Radial Velocity                553.0     823.354680    1454.926210   
Transit                        397.0      21.102073      46.185893   
Transit Timing Variations        3.0      79.783500      71.599884   

                                       min          25%           50%  \
method                                                                  
Astrometry                      246.360000   438.770000    631.180000   
Eclipse Timing Variations      1916.250000  2900.000000   4343.500000   
Imaging                        4639.150000  8343.900000  27500.000000   
Microlensing                   1825.000000  2375.000000   3300.000000   
Orbital Brightness Modulation     0.240104     0.291496      0.342887   
Pulsar Timing                     0.090706    25.262000     66.541900   
Pulsation Timing Variations    1170.000000  1170.000000   1170.000000   
Radial Velocity                   0.736540    38.021000    360.200000   
Transit                           0.355000     3.160630      5.714932   
Transit Timing Variations        22.339500    39.675250     57.011000   

                                        75%            max  
method                                                      
Astrometry                       823.590000    1016.000000  
Eclipse Timing Variations       5767.000000   10220.000000  
Imaging                        94250.000000  730000.000000  
Microlensing                    3550.000000    5100.000000  
Orbital Brightness Modulation      0.943908       1.544929  
Pulsar Timing                     98.211400   36525.000000  
Pulsation Timing Variations     1170.000000    1170.000000  
Radial Velocity                  982.000000   17337.500000  
Transit                           16.145700     331.600590  
Transit Timing Variations        108.505500     160.000000

## İleri Toplulaştırma İşlemleri (Aggregate,filter,transform,apply)

In [66]:
import pandas as pd 
import numpy as np

In [60]:
df = pd.DataFrame({'gruplar':['A','B','C','A','B','C'],
                  'degisken1': [10,23,33,22,11,99],
                  'degisken2': [100,253,333,262,111,969]},
                  columns =['gruplar','degisken1','degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

## Aggregate Fonksiyonu

In [63]:
df.groupby("gruplar").mean()

degisken1  degisken2
gruplar                      
A             16.0      181.0
B             17.0      182.0
C             66.0      651.0

In [70]:
df.groupby("gruplar").aggregate(["min",np.median,max]).T

gruplar               A      B      C
degisken1 min      10.0   11.0   33.0
          median   16.0   17.0   66.0
          max      22.0   23.0   99.0
degisken2 min     100.0  111.0  333.0
          median  181.0  182.0  651.0
          max     262.0  253.0  969.0

In [71]:
df.groupby("gruplar").aggregate({"degisken1":"min","degisken2":max})

degisken1  degisken2
gruplar                      
A               10        262
B               11        253
C               33        969

## Filter Fonksiyonu

In [72]:
df = pd.DataFrame({'gruplar':['A','B','C','A','B','C'],
                  'degisken1': [10,23,33,22,11,99],
                  'degisken2': [100,253,333,262,111,969]},
                  columns =['gruplar','degisken1','degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [73]:
def filter_func(x):
    return x["degisken1"].std()>9

In [75]:
df.groupby("gruplar").std()

degisken1   degisken2
gruplar                       
A         8.485281  114.551299
B         8.485281  100.409163
C        46.669048  449.719913

In [74]:
df.groupby("gruplar").filter(filter_func)

gruplar  degisken1  degisken2
2       C         33        333
5       C         99        969

## Transform Fonksiyonu

In [76]:
df = pd.DataFrame({'gruplar':['A','B','C','A','B','C'],
                  'degisken1': [10,23,33,22,11,99],
                  'degisken2': [100,253,333,262,111,969]},
                  columns =['gruplar','degisken1','degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [77]:
df["degisken1"]*9

0     90
1    207
2    297
3    198
4     99
5    891
Name: degisken1, dtype: int64

In [81]:
df_a = df.iloc[:,1:3]

In [83]:
df_a.transform(lambda x: (x-x.mean())/x.std())

degisken1  degisken2
0  -0.687871  -0.738461
1  -0.299074  -0.263736
2   0.000000  -0.015514
3  -0.328982  -0.235811
4  -0.657963  -0.704331
5   1.973890   1.957853

## Apply Fonksiyonu

In [96]:
df = pd.DataFrame({'gruplar':['A','B','C','A','B','C'],
                  'degisken1': [10,23,33,22,11,99],
                  'degisken2': [100,253,333,262,111,969]},
                  columns =['gruplar','degisken1','degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

* df = pd.DataFrame({
                  'degisken1': [10,23,33,22,11,99],
                  'degisken2': [100,253,333,262,111,969]},
                  columns =['degisken1','degisken2'])
* df

In [94]:
df.apply(np.sum) 

degisken1     198
degisken2    2028
dtype: int64

In [95]:
df.apply(np.mean)

degisken1     33.0
degisken2    338.0
dtype: float64

In [97]:
df.groupby("gruplar").apply(np.sum)

gruplar  degisken1  degisken2
gruplar                              
A            AA         32        362
B            BB         34        364
C            CC        132       1302

In [98]:
df.groupby("gruplar").apply(np.mean)

/opt/anaconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py:3417: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)


degisken1  degisken2
gruplar                      
A             16.0      181.0
B             17.0      182.0
C             66.0      651.0

# Pivot Tablolar

* Veri setleri üzerinde bazı satır ve sütun işlemleri yaparak veri setini amaca uygun hale getirmek için kullanılan yapılardır.
* groupby işlemleriyle karıştırılabilmektedir. groupbay'ın çok boyutlu versiyonu olarak düşünülebilir.

In [99]:
import pandas as pd
import seaborn as sns

titanic = sns. load_dataset('titanic')
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [101]:
titanic.groupby("sex")[["survived"]].mean()

survived
sex             
female  0.742038
male    0.188908

In [107]:
titanic.groupby(["sex","class"])[["survived"]].aggregate("mean")

survived
sex    class           
female First   0.968085
       Second  0.921053
       Third   0.500000
male   First   0.368852
       Second  0.157407
       Third   0.135447

In [108]:
titanic.groupby(["sex","class"])[["survived"]].aggregate("mean").unstack()

survived                    
class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

## Pivot ile table

In [109]:
titanic.pivot_table("survived",index = "sex", columns = "class")

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [111]:
titanic.age.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [113]:
age = pd.cut(titanic["age"],[0,18,90])
age.head(10)

0    (18.0, 90.0]
1    (18.0, 90.0]
2    (18.0, 90.0]
3    (18.0, 90.0]
4    (18.0, 90.0]
5             NaN
6    (18.0, 90.0]
7     (0.0, 18.0]
8    (18.0, 90.0]
9     (0.0, 18.0]
Name: age, dtype: category
Categories (2, interval[int64, right]): [(0, 18] < (18, 90]]

In [114]:
titanic.pivot_table("survived",["sex",age],"class")

class               First    Second     Third
sex    age                                   
female (0, 18]   0.909091  1.000000  0.511628
       (18, 90]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 90]  0.375000  0.071429  0.133663

# Dış Kaynaklı Veri Okumak

In [115]:
import pandas as pd

In [120]:
?pd.read_csv

Signature:
pd.read_csv(
    filepath_or_buffer: 'FilePathOrBuffer',
    sep=<no_default>,
    delimiter=None,
    header='infer',
    names=<no_default>,
    index_col=None,
    usecols=None,
    squeeze=False,
    prefix=<no_default>,
    mangle_dupe_cols=True,
    dtype: 'DtypeArg | None' = None,
    engine=None,
    converters=None,
    true_values=None,
    false_values=None,
    skipinitialspace=False,
    skiprows=None,
    skipfooter=0,
    nrows=None,
    na_values=None,
    keep_default_na=True,
    na_filter=True,
    verbose=False,
    skip_blank_lines=True,
    parse_dates=False,
    infer_datetime_format=False,
    keep_date_col=False,
    date_parser=None,
    dayfirst=False,
    cache_dates=True,
    iterator=False,
    chunksize=None,
    compression='infer',
    thousands=None,
    decimal: 'str' = '.',
    lineterminator=None,
    quotechar='"',
    quoting=0,
    doublequote=True,
    escapechar=None,
    comment=None,
    encoding=None,
    encoding_errors: 'str | N

In [118]:
#csv okuma
pd.read_csv("reading_data/ornekcsv.csv", sep = ";")

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [119]:
#txt okuma
pd.read_csv("reading_data/duz_metin.txt")

1 2
0   2 2
1   3 2
2   4 2
3   5 2
4   6 2
5  7 2 
6   8 2
7   9 2
8  10 2

In [121]:
#excel okuma 
pd.read_excel("reading_data/ornekx.xlsx")

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [122]:
df = pd.read_excel("reading_data/ornekx.xlsx")

In [123]:
type(df)

pandas.core.frame.DataFrame

In [124]:
df.head()

a    b    c
0  78   12  1.0
1  78   12  2.0
2  78  324  3.0
3   7    2  4.0
4  88   23  5.0

In [125]:
df.columns = ("A","B","C")
df

A    B     C
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [126]:
# Github'tan alınan verilerin txt dosyasına atılması(raw şekilde) ve okunması
tips = pd.read_csv("reading_data/data.txt")

In [128]:
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

# Bonus: Problem Çözme ve Doküman Okuma Kültürü

* %95 Yapısal Problemler ve Veri Ön İşleme 
* %5 Modelleme ve benzer işler